// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVpxqgsEde3dXNvek0MJvyUBsO1Hm_I2o',
    appId: '1:672681211485:web:1e6b1639eeced82a7d3fb4',
    messagingSenderId: '672681211485',
    projectId: 'resume-analyzer-d14f4',
    authDomain: 'resume-analyzer-d14f4.firebaseapp.com',
    storageBucket: 'resume-analyzer-d14f4.firebasestorage.app',
    measurementId: 'G-ET6K3M7N9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWhe3xFlaBewqcJWtjfbTn6HSLrYZKvZw',
    appId: '1:672681211485:android:8fba6c70dd0796bc7d3fb4',
    messagingSenderId: '672681211485',
    projectId: 'resume-analyzer-d14f4',
    storageBucket: 'resume-analyzer-d14f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsLZdDk8PX7rSENbXxBC6K0lOKeTRLttM',
    appId: '1:672681211485:ios:8f106d0648ab4ad37d3fb4',
    messagingSenderId: '672681211485',
    projectId: 'resume-analyzer-d14f4',
    storageBucket: 'resume-analyzer-d14f4.firebasestorage.app',
    iosBundleId: 'com.example.smartInterviewAnalyzer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsLZdDk8PX7rSENbXxBC6K0lOKeTRLttM',
    appId: '1:672681211485:ios:8f106d0648ab4ad37d3fb4',
    messagingSenderId: '672681211485',
    projectId: 'resume-analyzer-d14f4',
    storageBucket: 'resume-analyzer-d14f4.firebasestorage.app',
    iosBundleId: 'com.example.smartInterviewAnalyzer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVpxqgsEde3dXNvek0MJvyUBsO1Hm_I2o',
    appId: '1:672681211485:web:a9f32f74c129a3b77d3fb4',
    messagingSenderId: '672681211485',
    projectId: 'resume-analyzer-d14f4',
    authDomain: 'resume-analyzer-d14f4.firebaseapp.com',
    storageBucket: 'resume-analyzer-d14f4.firebasestorage.app',
    measurementId: 'G-GFDKEBNKVB',
  );
}
